### PR TITLE
Second draft

### PR DESCRIPTION
**Pull request by dpk**
To quote the commit message, which adequately summarizes the changes:

> Deleted bytevector-bisect-* procedures, as they're probably unlikely
> to be useful in practice. In their place, I show how to use the new
> define-bisection syntax to get them back. The sample implementation
> now also uses the new define-bisection syntax to define the procedures
> on vectors.

I’d like to offer a bit of commentary on this and on the new issue listed in the ‘issues’ section for the mailing list to discuss.

Providing syntax for `define-bisection` seems like overkill, and probably is. I’d much prefer a procedure, `bisection`, which would return two values, the procedure for the left bisection and the right bisection respectively. However, there would then be no elegant way to bind those to names at the top level in R7RS small, as R7RS small has no `define-values` (nor does R6RS or R5RS, and although some implementations define it and a Google search for [site:srfi.schemers.org "define-values"] shows it’s been used to demonstrate some SRFIs, it apparently hasn’t been standardized. [Footnote: It would be extremely useful to have a symbol index to all SRFIs so we can look up what defines what without resorting to Google.]). In order to get them at the top level, you’d have to do something like this:

```scheme
(define x-bisect-left #f)
(define x-bisect-right #f)

(let-values (((left-proc right-proc) (bisection x-ref)))
  ;; This is a new lexical environment, so we can’t put the define forms directly
  ;; here or they’ll be treated as local to the let, and not bound at the top level.
  ;; The same applies to any other method of capturing multiple return values
  ;; provided by R7RS small.
  (set! x-bisect-left left-proc)
  (set! x-bisect-right right-proc))
```

However inelegant it is to define syntax for this one case, I’m sure everyone can agree the above is far worse. The ideal is:

```scheme
(define-values (x-bisect-left x-bisect-right) (bisection x-ref))
```

One option would be separate `left-bisection` and `right-bisection` procedures returning one procedure each. But that still means repeating not only the ref-proc, but also the lo-hi-proc (likely a lambda) if one is provided (and I expect one will be in most cases, as most vectors have a known size), and I’d rather force (or at least encourage) people to be consistent about always defining the right bisection if they define the left, and vice-versa.

As the point of providing this is convenience, I think I’d like to provide the most convenient possible thing — and the most convenient *possible* thing (emphasis deliberate) is a `define-bisection` special form. But I’m open to other ideas.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
R7RS Small does, in fact, define define-values.  See p. 26.

I'm working on a symbol index for SRFIs, but it's taking me a long time.  I
do a few SRFIs a week in my spare time.

I'll wait to publish this draft until I hear back from you, just in case
you want to refine it in light of define-values actually having been
standardized.

**Comment by dpk** [comment]
Oh! D’oh! And here’s me sitting on the draft an extra day so I would have time to proofread. I was looking in the list of symbols exported by `(scheme base)` and but missed it both times, probably because I didn’t notice that the list is alphabetized in two columns in

```
A B
C D
```

order, not

```
A C
B D
```

order.

Right. What a lot of hot air I wasted over nothing. 🤦🏼‍♀️ I’ll revise the second draft to get rid of this issue entirely. Thanks for pointing out the bleeding obvious, because I missed it as usual.

**Comment by arthurgleckler** [comment]
Don't give yourself a hard time.  We really do need an index, not just for
the SRFIs, but also for the RnRS reports.  A few of us are working on that,
but progress is slow.  (There have been some discussions on schemedoc
<https://srfi-email.schemers.org/schemedoc/>.)

>

**Comment by dpk** [comment]
Okay, updated. I hope the notation I use to show returning 2 procedures which each take multiple possible argument patterns is clear enough.

**Pull request merged**
